apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-dbupdater-cronjob
spec:
  schedule: {{ .Values.workers.dbupdaterSchedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: dbupdater
              image: postgres:15-alpine
              command:
                - /bin/sh
                - -c
                - |
                  echo "Recherche de fichiers SQL dans /app/updates..."
                  if ls /app/updates/*.sql 1> /dev/null 2>&1; then
                    for file in /app/updates/*.sql; do
                      if [ -f "$file" ]; then
                        echo "Exécution de $file..."
                        psql -h {{ .Release.Name }}-db -U $POSTGRES_USER -d $POSTGRES_DB -f "$file" || exit 1
                        echo "Suppression de $file pour éviter une double exécution..."
                        rm "$file"
                      fi
                    done
                    echo "Mise à jour terminée."
                  else
                    echo "Aucun fichier d'update SQL trouvé."
                  fi
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-db-secret
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-db-secret
                      key: POSTGRES_USER
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-db-secret
                      key: POSTGRES_DB
              volumeMounts:
                - name: shared-data
                  mountPath: /app/updates
                  subPath: updates
          volumes:
            - name: shared-data
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-shared-pvc
